multi_branch_env:
  hostname: tr.rt.gw
  user: root
  site_url: https://ishita-sagar-jagtap.tr.rt.gw
  main_site: ishita-sagar-jagtap.tr.rt.gw
  deploy_path: /opt/easyengine/sites/ishita-sagar-jagtap.tr.rt.gw/app/htdocs
